name: ">>>> Docker testing"
on: push

jobs:
  run_container:
    name: Run container
    runs-on: ubuntu-latest
    steps:
      - name: uname
        run: |
          uname -a
          whoami
          pwd
          ls

      - name: install qemu
        run: |
          sudo apt-get update -y
          sudo apt-get install qemu binfmt-support qemu-user-static -y
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

          docker run --rm -t arm64v8/ubuntu uname -m
